#!/usr/bin/env bash

echo "Installing Homebrew and git ..."
  sudo mkdir -p /usr/local
  sudo chown -R `whoami` /usr/local
  /usr/bin/ruby -e "$(curl -fsSL https://raw.github.com/gist/323731)"
  echo "export PATH=/usr/local/bin:$PATH" >> ~/.bash_profile
  export PATH=/usr/local/bin:$PATH
  brew install git
  brew update

echo "Installing Postgres, a good open source relational database ..."
  brew install postgres --no-python
  initdb /usr/local/var/postgres
  mkdir -p ~/Library/LaunchAgents
  cp /usr/local/Cellar/postgresql/9.0.4/org.postgresql.postgres.plist ~/Library/LaunchAgents/
  launchctl load -w ~/Library/LaunchAgents/org.postgresql.postgres.plist

echo "Installing RVM (Ruby Version Manager) ..."
  curl -s https://rvm.beginrescueend.com/install/rvm -o rvm-installer ; chmod +x rvm-installer ; ./rvm-installer --version latest
echo "[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.bash_profile
  source ~/.bash_profile

bash < <(curl -s https://raw.github.com/myfreecomm/development-setup/master/ruby)